(cl:defpackage rosbridge_library-msg
  (:use )
  (:export
   "<TESTTIMEARRAY>"
   "TESTTIMEARRAY"
   "<TESTDURATIONARRAY>"
   "TESTDURATIONARRAY"
   "<TESTUINT8>"
   "TESTUINT8"
   "<NUM>"
   "NUM"
   "<TESTUINT8FIXEDSIZEARRAY16>"
   "TESTUINT8FIXEDSIZEARRAY16"
   "<TESTCHAR>"
   "TESTCHAR"
   "<TESTHEADER>"
   "TESTHEADER"
   "<TESTHEADERTWO>"
   "TESTHEADERTWO"
   "<TESTHEADERARRAY>"
   "TESTHEADERARRAY"
  ))

